import typing
import ex1

if __name__ == "__main__":
    print("=== Healing Part ===")
    print("= base =")
    new_healfac: typing.Any = ex1.HealingCreatureFactory()
    new_sprout: typing.Any = new_healfac.create_base()
    new_bloome: typing.Any = new_healfac.create_evolved()
    print(f"{new_sprout.describe()}")
    print(f"{new_sprout.attack()}")
    print(f"{new_sprout.heal()}")
    print("= evolved =")
    print(f"{new_bloome.describe()}")
    print(f"{new_bloome.attack()}")
    print(f"{new_bloome.heal()}")
    print()
    print("=== Transform Part ===")
    print("= base =")
    new_trafac: typing.Any = ex1.TransformCreatureFactory()
    new_shift: typing.Any = new_trafac.create_base()
    new_morp: typing.Any = new_trafac.create_evolved()
    print(f"{new_shift.describe()}")
    print(f"{new_shift.attack()}")
    print(f"{new_shift.transform()}")
    print(f"{new_shift.attack()}")
    print(f"{new_shift.revert()}")
    print("= evolved =")
    print(f"{new_morp.describe()}")
    print(f"{new_morp.attack()}")
    print(f"{new_morp.transform()}")
    print(f"{new_morp.attack()}")
    print(f"{new_morp.revert()}")
